AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template installs an EC2 instance with Kamailio & Siremis installed
Parameters:
  YourPublicIP:
    Description: 'Use the command "curl ifconfig.me" to find out your public IP address and use /32 as mask'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.10.10.10/32
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP address in the x.x.x.x/x format
Resources:
  SIP:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0bd4489885512c160
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref SIPSecurityGroup
      KeyName: "siptopia"
  MyEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref SIP
  SIPSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: EnableSIPhttpSSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref YourPublicIP
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref YourPublicIP
        - IpProtocol: tcp
          FromPort: '5060'
          ToPort: '5060'
          CidrIp: !Ref YourPublicIP
        - IpProtocol: udp
          FromPort: '5060'
          ToPort: '5060'
          CidrIp: !Ref YourPublicIP
